/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * The version of the OpenAPI document: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddBankToTransaction model module.
 * @module model/AddBankToTransaction
 * @version v1
 */
class AddBankToTransaction {
    /**
     * Constructs a new <code>AddBankToTransaction</code>.
     * @alias module:model/AddBankToTransaction
     * @param transaction {Number} Transaction ID
     * @param bank {module:model/AddBankToTransaction.BankEnum} Bank code
     * @param accountName {String} Account name
     * @param accountNumber {String} Account number
     */
    constructor(transaction, bank, accountName, accountNumber) { 
        
        AddBankToTransaction.initialize(this, transaction, bank, accountName, accountNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transaction, bank, accountName, accountNumber) { 
        obj['transaction'] = transaction;
        obj['bank'] = bank;
        obj['account_name'] = accountName;
        obj['account_number'] = accountNumber;
    }

    /**
     * Constructs a <code>AddBankToTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddBankToTransaction} obj Optional instance to populate.
     * @return {module:model/AddBankToTransaction} The populated <code>AddBankToTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddBankToTransaction();

            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = ApiClient.convertToType(data['transaction'], 'Number');
            }
            if (data.hasOwnProperty('bank')) {
                obj['bank'] = ApiClient.convertToType(data['bank'], 'String');
            }
            if (data.hasOwnProperty('account_name')) {
                obj['account_name'] = ApiClient.convertToType(data['account_name'], 'String');
            }
            if (data.hasOwnProperty('account_number')) {
                obj['account_number'] = ApiClient.convertToType(data['account_number'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddBankToTransaction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddBankToTransaction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddBankToTransaction.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bank'] && !(typeof data['bank'] === 'string' || data['bank'] instanceof String)) {
            throw new Error("Expected the field `bank` to be a primitive type in the JSON string but got " + data['bank']);
        }
        // ensure the json data is a string
        if (data['account_name'] && !(typeof data['account_name'] === 'string' || data['account_name'] instanceof String)) {
            throw new Error("Expected the field `account_name` to be a primitive type in the JSON string but got " + data['account_name']);
        }
        // ensure the json data is a string
        if (data['account_number'] && !(typeof data['account_number'] === 'string' || data['account_number'] instanceof String)) {
            throw new Error("Expected the field `account_number` to be a primitive type in the JSON string but got " + data['account_number']);
        }

        return true;
    }


}

AddBankToTransaction.RequiredProperties = ["transaction", "bank", "account_name", "account_number"];

/**
 * Transaction ID
 * @member {Number} transaction
 */
AddBankToTransaction.prototype['transaction'] = undefined;

/**
 * Bank code
 * @member {module:model/AddBankToTransaction.BankEnum} bank
 */
AddBankToTransaction.prototype['bank'] = undefined;

/**
 * Account name
 * @member {String} account_name
 */
AddBankToTransaction.prototype['account_name'] = undefined;

/**
 * Account number
 * @member {String} account_number
 */
AddBankToTransaction.prototype['account_number'] = undefined;





/**
 * Allowed values for the <code>bank</code> property.
 * @enum {String}
 * @readonly
 */
AddBankToTransaction['BankEnum'] = {

    /**
     * value: "044"
     * @const
     */
    "044": "044",

    /**
     * value: "023"
     * @const
     */
    "023": "023",

    /**
     * value: "063"
     * @const
     */
    "063": "063",

    /**
     * value: "050"
     * @const
     */
    "050": "050",

    /**
     * value: "070"
     * @const
     */
    "070": "070",

    /**
     * value: "011"
     * @const
     */
    "011": "011",

    /**
     * value: "214"
     * @const
     */
    "214": "214",

    /**
     * value: "058"
     * @const
     */
    "058": "058",

    /**
     * value: "030"
     * @const
     */
    "030": "030",

    /**
     * value: "301"
     * @const
     */
    "301": "301",

    /**
     * value: "082"
     * @const
     */
    "082": "082",

    /**
     * value: "014"
     * @const
     */
    "014": "014",

    /**
     * value: "076"
     * @const
     */
    "076": "076",

    /**
     * value: "039"
     * @const
     */
    "039": "039",

    /**
     * value: "232"
     * @const
     */
    "232": "232",

    /**
     * value: "032"
     * @const
     */
    "032": "032",

    /**
     * value: "033"
     * @const
     */
    "033": "033",

    /**
     * value: "215"
     * @const
     */
    "215": "215",

    /**
     * value: "035"
     * @const
     */
    "035": "035",

    /**
     * value: "057"
     * @const
     */
    "057": "057"
};



export default AddBankToTransaction;

