/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * The version of the OpenAPI document: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Owner from './Owner';
import Sharing from './Sharing';

/**
 * The Folder model module.
 * @module model/Folder
 * @version v1
 */
class Folder {
    /**
     * Constructs a new <code>Folder</code>.
     * @alias module:model/Folder
     * @param sharing {Array.<module:model/Sharing>} 
     * @param owner {module:model/Owner} 
     * @param metaData {Object} 
     * @param stats {Object} 
     * @param name {String} 
     */
    constructor(sharing, owner, metaData, stats, name) { 
        
        Folder.initialize(this, sharing, owner, metaData, stats, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sharing, owner, metaData, stats, name) { 
        obj['sharing'] = sharing;
        obj['owner'] = owner;
        obj['meta_data'] = metaData;
        obj['stats'] = stats;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Folder</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Folder} obj Optional instance to populate.
     * @return {module:model/Folder} The populated <code>Folder</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Folder();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('sharing')) {
                obj['sharing'] = ApiClient.convertToType(data['sharing'], [Sharing]);
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = Owner.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('meta_data')) {
                obj['meta_data'] = ApiClient.convertToType(data['meta_data'], Object);
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = ApiClient.convertToType(data['stats'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('is_module_folder')) {
                obj['is_module_folder'] = ApiClient.convertToType(data['is_module_folder'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Folder</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Folder</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Folder.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['sharing']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sharing'])) {
                throw new Error("Expected the field `sharing` to be an array in the JSON data but got " + data['sharing']);
            }
            // validate the optional field `sharing` (array)
            for (const item of data['sharing']) {
                Sharing.validateJsonObject(item);
            };
        }
        // validate the optional field `owner`
        if (data['owner']) { // data not null
          Owner.validateJSON(data['owner']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

Folder.RequiredProperties = ["sharing", "owner", "meta_data", "stats", "name"];

/**
 * @member {Number} id
 */
Folder.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/Sharing>} sharing
 */
Folder.prototype['sharing'] = undefined;

/**
 * @member {module:model/Owner} owner
 */
Folder.prototype['owner'] = undefined;

/**
 * @member {Object} meta_data
 */
Folder.prototype['meta_data'] = undefined;

/**
 * @member {Object} stats
 */
Folder.prototype['stats'] = undefined;

/**
 * @member {String} name
 */
Folder.prototype['name'] = undefined;

/**
 * @member {Date} created_at
 */
Folder.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Folder.prototype['updated_at'] = undefined;

/**
 * @member {Boolean} is_module_folder
 */
Folder.prototype['is_module_folder'] = undefined;

/**
 * @member {String} type
 */
Folder.prototype['type'] = undefined;

/**
 * @member {Number} parent
 */
Folder.prototype['parent'] = undefined;






export default Folder;

