/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * The version of the OpenAPI document: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Sharing model module.
 * @module model/Sharing
 * @version v1
 */
class Sharing {
    /**
     * Constructs a new <code>Sharing</code>.
     * @alias module:model/Sharing
     * @param user {Number} 
     */
    constructor(user) { 
        
        Sharing.initialize(this, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user) { 
        obj['user'] = user;
    }

    /**
     * Constructs a <code>Sharing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Sharing} obj Optional instance to populate.
     * @return {module:model/Sharing} The populated <code>Sharing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sharing();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('can_read')) {
                obj['can_read'] = ApiClient.convertToType(data['can_read'], 'Boolean');
            }
            if (data.hasOwnProperty('can_edit')) {
                obj['can_edit'] = ApiClient.convertToType(data['can_edit'], 'Boolean');
            }
            if (data.hasOwnProperty('can_delete')) {
                obj['can_delete'] = ApiClient.convertToType(data['can_delete'], 'Boolean');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'Number');
            }
            if (data.hasOwnProperty('folder')) {
                obj['folder'] = ApiClient.convertToType(data['folder'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Sharing</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Sharing</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Sharing.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

Sharing.RequiredProperties = ["user"];

/**
 * @member {Number} id
 */
Sharing.prototype['id'] = undefined;

/**
 * @member {Boolean} can_read
 */
Sharing.prototype['can_read'] = undefined;

/**
 * @member {Boolean} can_edit
 */
Sharing.prototype['can_edit'] = undefined;

/**
 * @member {Boolean} can_delete
 */
Sharing.prototype['can_delete'] = undefined;

/**
 * @member {Number} user
 */
Sharing.prototype['user'] = undefined;

/**
 * @member {Number} file
 */
Sharing.prototype['file'] = undefined;

/**
 * @member {Number} folder
 */
Sharing.prototype['folder'] = undefined;






export default Sharing;

