/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * The version of the OpenAPI document: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LoanAndAdvance from '../model/LoanAndAdvance';
import LoansAndAdvancesList200Response from '../model/LoansAndAdvancesList200Response';

/**
* LoansAndAdvances service.
* @module api/LoansAndAdvancesApi
* @version v1
*/
export default class LoansAndAdvancesApi {

    /**
    * Constructs a new LoansAndAdvancesApi. 
    * @alias module:api/LoansAndAdvancesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the loansAndAdvancesApprove operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesApproveCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this loan and advance.
     * @param {Object.<String, Object>} data 
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesApproveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    loansAndAdvancesApprove(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling loansAndAdvancesApprove");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling loansAndAdvancesApprove");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/loans-and-advances/{id}/approve/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loansAndAdvancesCreate operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LoanAndAdvance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/LoanAndAdvance} data 
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LoanAndAdvance}
     */
    loansAndAdvancesCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling loansAndAdvancesCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LoanAndAdvance;
      return this.apiClient.callApi(
        '/loans-and-advances/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loansAndAdvancesDecline operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesDeclineCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this loan and advance.
     * @param {Object.<String, Object>} data 
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesDeclineCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    loansAndAdvancesDecline(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling loansAndAdvancesDecline");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling loansAndAdvancesDecline");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/loans-and-advances/{id}/decline/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loansAndAdvancesDelete operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this loan and advance.
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    loansAndAdvancesDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling loansAndAdvancesDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/loans-and-advances/{id}/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loansAndAdvancesList operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LoansAndAdvancesList200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page A page number within the paginated result set.
     * @param {Number} opts.pageSize Number of results to return per page.
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LoansAndAdvancesList200Response}
     */
    loansAndAdvancesList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'page_size': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LoansAndAdvancesList200Response;
      return this.apiClient.callApi(
        '/loans-and-advances/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loansAndAdvancesPartialUpdate operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesPartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LoanAndAdvance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this loan and advance.
     * @param {module:model/LoanAndAdvance} data 
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LoanAndAdvance}
     */
    loansAndAdvancesPartialUpdate(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling loansAndAdvancesPartialUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling loansAndAdvancesPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LoanAndAdvance;
      return this.apiClient.callApi(
        '/loans-and-advances/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loansAndAdvancesRead operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesReadCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LoanAndAdvance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this loan and advance.
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesReadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LoanAndAdvance}
     */
    loansAndAdvancesRead(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling loansAndAdvancesRead");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LoanAndAdvance;
      return this.apiClient.callApi(
        '/loans-and-advances/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loansAndAdvancesUpdate operation.
     * @callback module:api/LoansAndAdvancesApi~loansAndAdvancesUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LoanAndAdvance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this loan and advance.
     * @param {module:model/LoanAndAdvance} data 
     * @param {module:api/LoansAndAdvancesApi~loansAndAdvancesUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LoanAndAdvance}
     */
    loansAndAdvancesUpdate(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling loansAndAdvancesUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling loansAndAdvancesUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LoanAndAdvance;
      return this.apiClient.callApi(
        '/loans-and-advances/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
