/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * The version of the OpenAPI document: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NgdlApi);
  }
}(this, function(expect, NgdlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NgdlApi.EmployeeGroup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmployeeGroup', function() {
    it('should create an instance of EmployeeGroup', function() {
      // uncomment below and update the code to test EmployeeGroup
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be.a(NgdlApi.EmployeeGroup);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property baseSalary (base name: "base_salary")', function() {
      // uncomment below and update the code to test the property baseSalary
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property pensionPercent (base name: "pension_percent")', function() {
      // uncomment below and update the code to test the property pensionPercent
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property taxPercent (base name: "tax_percent")', function() {
      // uncomment below and update the code to test the property taxPercent
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property loanInterestRate (base name: "loan_interest_rate")', function() {
      // uncomment below and update the code to test the property loanInterestRate
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property advanceInterestRate (base name: "advance_interest_rate")', function() {
      // uncomment below and update the code to test the property advanceInterestRate
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property canTakeLoan (base name: "can_take_loan")', function() {
      // uncomment below and update the code to test the property canTakeLoan
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property canTakeAdvance (base name: "can_take_advance")', function() {
      // uncomment below and update the code to test the property canTakeAdvance
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new NgdlApi.EmployeeGroup();
      //expect(instance).to.be();
    });

  });

}));
