/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * The version of the OpenAPI document: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddBankToTransaction from './model/AddBankToTransaction';
import Allowance from './model/Allowance';
import AllowancesList200Response from './model/AllowancesList200Response';
import ApprovalForm from './model/ApprovalForm';
import Asset from './model/Asset';
import AssetsList200Response from './model/AssetsList200Response';
import Budget from './model/Budget';
import BudgetCycle from './model/BudgetCycle';
import BudgetCyclesList200Response from './model/BudgetCyclesList200Response';
import BudgetsList200Response from './model/BudgetsList200Response';
import CategoriesList200Response from './model/CategoriesList200Response';
import Category from './model/Category';
import Deduction from './model/Deduction';
import DeductionsList200Response from './model/DeductionsList200Response';
import Department from './model/Department';
import DepartmentsList200Response from './model/DepartmentsList200Response';
import Employee from './model/Employee';
import EmployeeGroup from './model/EmployeeGroup';
import EmployeeGroupsList200Response from './model/EmployeeGroupsList200Response';
import EmployeesList200Response from './model/EmployeesList200Response';
import File from './model/File';
import FilesList200Response from './model/FilesList200Response';
import Folder from './model/Folder';
import FoldersList200Response from './model/FoldersList200Response';
import LeaveAndHoliday from './model/LeaveAndHoliday';
import LeaveAndHolidaysList200Response from './model/LeaveAndHolidaysList200Response';
import LoanAndAdvance from './model/LoanAndAdvance';
import LoansAndAdvancesList200Response from './model/LoansAndAdvancesList200Response';
import Owner from './model/Owner';
import Payroll from './model/Payroll';
import PayrollsList200Response from './model/PayrollsList200Response';
import Payslip from './model/Payslip';
import PayslipsList200Response from './model/PayslipsList200Response';
import ProfiLossForm from './model/ProfiLossForm';
import Sharing from './model/Sharing';
import Training from './model/Training';
import TrainingsList200Response from './model/TrainingsList200Response';
import Transaction from './model/Transaction';
import TransactionsExpenseList200Response from './model/TransactionsExpenseList200Response';
import TransactionsList200Response from './model/TransactionsList200Response';
import AllowancesApi from './api/AllowancesApi';
import AssetsApi from './api/AssetsApi';
import BudgetCyclesApi from './api/BudgetCyclesApi';
import BudgetsApi from './api/BudgetsApi';
import CategoriesApi from './api/CategoriesApi';
import DeductionsApi from './api/DeductionsApi';
import DepartmentsApi from './api/DepartmentsApi';
import EmployeeGroupsApi from './api/EmployeeGroupsApi';
import EmployeesApi from './api/EmployeesApi';
import FilesApi from './api/FilesApi';
import FoldersApi from './api/FoldersApi';
import LeaveAndHolidaysApi from './api/LeaveAndHolidaysApi';
import LoansAndAdvancesApi from './api/LoansAndAdvancesApi';
import PayrollsApi from './api/PayrollsApi';
import PayslipsApi from './api/PayslipsApi';
import TrainingsApi from './api/TrainingsApi';
import TransactionsApi from './api/TransactionsApi';


/**
*  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.&lt;br/&gt;&lt;br/&gt; The API is currently in version &lt;b&gt;1.0.0&lt;/b&gt;.&lt;br/&gt; Developed by: &lt;b&gt;The Boolean Technology Ltd.&lt;/b&gt;&lt;br/&gt; Developed for: &lt;b&gt;Nehemiah Grace Developer Limited&lt;/b&gt;&lt;br/&gt; .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NgdlApi = require('index'); // See note below*.
* var xxxSvc = new NgdlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NgdlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NgdlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NgdlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddBankToTransaction model constructor.
     * @property {module:model/AddBankToTransaction}
     */
    AddBankToTransaction,

    /**
     * The Allowance model constructor.
     * @property {module:model/Allowance}
     */
    Allowance,

    /**
     * The AllowancesList200Response model constructor.
     * @property {module:model/AllowancesList200Response}
     */
    AllowancesList200Response,

    /**
     * The ApprovalForm model constructor.
     * @property {module:model/ApprovalForm}
     */
    ApprovalForm,

    /**
     * The Asset model constructor.
     * @property {module:model/Asset}
     */
    Asset,

    /**
     * The AssetsList200Response model constructor.
     * @property {module:model/AssetsList200Response}
     */
    AssetsList200Response,

    /**
     * The Budget model constructor.
     * @property {module:model/Budget}
     */
    Budget,

    /**
     * The BudgetCycle model constructor.
     * @property {module:model/BudgetCycle}
     */
    BudgetCycle,

    /**
     * The BudgetCyclesList200Response model constructor.
     * @property {module:model/BudgetCyclesList200Response}
     */
    BudgetCyclesList200Response,

    /**
     * The BudgetsList200Response model constructor.
     * @property {module:model/BudgetsList200Response}
     */
    BudgetsList200Response,

    /**
     * The CategoriesList200Response model constructor.
     * @property {module:model/CategoriesList200Response}
     */
    CategoriesList200Response,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The Deduction model constructor.
     * @property {module:model/Deduction}
     */
    Deduction,

    /**
     * The DeductionsList200Response model constructor.
     * @property {module:model/DeductionsList200Response}
     */
    DeductionsList200Response,

    /**
     * The Department model constructor.
     * @property {module:model/Department}
     */
    Department,

    /**
     * The DepartmentsList200Response model constructor.
     * @property {module:model/DepartmentsList200Response}
     */
    DepartmentsList200Response,

    /**
     * The Employee model constructor.
     * @property {module:model/Employee}
     */
    Employee,

    /**
     * The EmployeeGroup model constructor.
     * @property {module:model/EmployeeGroup}
     */
    EmployeeGroup,

    /**
     * The EmployeeGroupsList200Response model constructor.
     * @property {module:model/EmployeeGroupsList200Response}
     */
    EmployeeGroupsList200Response,

    /**
     * The EmployeesList200Response model constructor.
     * @property {module:model/EmployeesList200Response}
     */
    EmployeesList200Response,

    /**
     * The File model constructor.
     * @property {module:model/File}
     */
    File,

    /**
     * The FilesList200Response model constructor.
     * @property {module:model/FilesList200Response}
     */
    FilesList200Response,

    /**
     * The Folder model constructor.
     * @property {module:model/Folder}
     */
    Folder,

    /**
     * The FoldersList200Response model constructor.
     * @property {module:model/FoldersList200Response}
     */
    FoldersList200Response,

    /**
     * The LeaveAndHoliday model constructor.
     * @property {module:model/LeaveAndHoliday}
     */
    LeaveAndHoliday,

    /**
     * The LeaveAndHolidaysList200Response model constructor.
     * @property {module:model/LeaveAndHolidaysList200Response}
     */
    LeaveAndHolidaysList200Response,

    /**
     * The LoanAndAdvance model constructor.
     * @property {module:model/LoanAndAdvance}
     */
    LoanAndAdvance,

    /**
     * The LoansAndAdvancesList200Response model constructor.
     * @property {module:model/LoansAndAdvancesList200Response}
     */
    LoansAndAdvancesList200Response,

    /**
     * The Owner model constructor.
     * @property {module:model/Owner}
     */
    Owner,

    /**
     * The Payroll model constructor.
     * @property {module:model/Payroll}
     */
    Payroll,

    /**
     * The PayrollsList200Response model constructor.
     * @property {module:model/PayrollsList200Response}
     */
    PayrollsList200Response,

    /**
     * The Payslip model constructor.
     * @property {module:model/Payslip}
     */
    Payslip,

    /**
     * The PayslipsList200Response model constructor.
     * @property {module:model/PayslipsList200Response}
     */
    PayslipsList200Response,

    /**
     * The ProfiLossForm model constructor.
     * @property {module:model/ProfiLossForm}
     */
    ProfiLossForm,

    /**
     * The Sharing model constructor.
     * @property {module:model/Sharing}
     */
    Sharing,

    /**
     * The Training model constructor.
     * @property {module:model/Training}
     */
    Training,

    /**
     * The TrainingsList200Response model constructor.
     * @property {module:model/TrainingsList200Response}
     */
    TrainingsList200Response,

    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction,

    /**
     * The TransactionsExpenseList200Response model constructor.
     * @property {module:model/TransactionsExpenseList200Response}
     */
    TransactionsExpenseList200Response,

    /**
     * The TransactionsList200Response model constructor.
     * @property {module:model/TransactionsList200Response}
     */
    TransactionsList200Response,

    /**
    * The AllowancesApi service constructor.
    * @property {module:api/AllowancesApi}
    */
    AllowancesApi,

    /**
    * The AssetsApi service constructor.
    * @property {module:api/AssetsApi}
    */
    AssetsApi,

    /**
    * The BudgetCyclesApi service constructor.
    * @property {module:api/BudgetCyclesApi}
    */
    BudgetCyclesApi,

    /**
    * The BudgetsApi service constructor.
    * @property {module:api/BudgetsApi}
    */
    BudgetsApi,

    /**
    * The CategoriesApi service constructor.
    * @property {module:api/CategoriesApi}
    */
    CategoriesApi,

    /**
    * The DeductionsApi service constructor.
    * @property {module:api/DeductionsApi}
    */
    DeductionsApi,

    /**
    * The DepartmentsApi service constructor.
    * @property {module:api/DepartmentsApi}
    */
    DepartmentsApi,

    /**
    * The EmployeeGroupsApi service constructor.
    * @property {module:api/EmployeeGroupsApi}
    */
    EmployeeGroupsApi,

    /**
    * The EmployeesApi service constructor.
    * @property {module:api/EmployeesApi}
    */
    EmployeesApi,

    /**
    * The FilesApi service constructor.
    * @property {module:api/FilesApi}
    */
    FilesApi,

    /**
    * The FoldersApi service constructor.
    * @property {module:api/FoldersApi}
    */
    FoldersApi,

    /**
    * The LeaveAndHolidaysApi service constructor.
    * @property {module:api/LeaveAndHolidaysApi}
    */
    LeaveAndHolidaysApi,

    /**
    * The LoansAndAdvancesApi service constructor.
    * @property {module:api/LoansAndAdvancesApi}
    */
    LoansAndAdvancesApi,

    /**
    * The PayrollsApi service constructor.
    * @property {module:api/PayrollsApi}
    */
    PayrollsApi,

    /**
    * The PayslipsApi service constructor.
    * @property {module:api/PayslipsApi}
    */
    PayslipsApi,

    /**
    * The TrainingsApi service constructor.
    * @property {module:api/TrainingsApi}
    */
    TrainingsApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:api/TransactionsApi}
    */
    TransactionsApi
};
