/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * OpenAPI spec version: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Category } from '../models/Category';
import { Folder } from '../models/Folder';
import { HttpFile } from '../http/http';

export class Asset {
    'id'?: number;
    'folder': Folder;
    'category': Category;
    'assetValue': number;
    'assetAge': number;
    'mediaGallery'?: string;
    'name': string;
    'code'?: string;
    'purchaseForm': string;
    'purchaseDate'?: string;
    'purchasePrice'?: number;
    'purchaseFrom': string;
    'hasWarranty'?: boolean;
    'warrantyDate'?: string;
    'warrantyFrom'?: string;
    'warrantyTo'?: string;
    'warrantyCost'?: number;
    'warrantyNote'?: string;
    'warrantyStatus'?: string;
    'isPhysical'?: boolean;
    'isMovable'?: boolean;
    'annualDepreciation'?: number;
    'isDepreciable'?: boolean;
    'location'?: string;
    'description'?: string;
    'status'?: AssetStatusEnum;
    'condition'?: AssetConditionEnum;
    'frequencyOfMaintenance'?: AssetFrequencyOfMaintenanceEnum;
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'image'?: number;
    'createdBy'?: number;
    'transactions': Set<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "Folder",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "Category",
            "format": ""
        },
        {
            "name": "assetValue",
            "baseName": "asset_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "assetAge",
            "baseName": "asset_age",
            "type": "number",
            "format": ""
        },
        {
            "name": "mediaGallery",
            "baseName": "media_gallery",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "purchaseForm",
            "baseName": "purchase_form",
            "type": "string",
            "format": ""
        },
        {
            "name": "purchaseDate",
            "baseName": "purchase_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "purchasePrice",
            "baseName": "purchase_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "purchaseFrom",
            "baseName": "purchase_from",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasWarranty",
            "baseName": "has_warranty",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "warrantyDate",
            "baseName": "warranty_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "warrantyFrom",
            "baseName": "warranty_from",
            "type": "string",
            "format": ""
        },
        {
            "name": "warrantyTo",
            "baseName": "warranty_to",
            "type": "string",
            "format": ""
        },
        {
            "name": "warrantyCost",
            "baseName": "warranty_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "warrantyNote",
            "baseName": "warranty_note",
            "type": "string",
            "format": ""
        },
        {
            "name": "warrantyStatus",
            "baseName": "warranty_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPhysical",
            "baseName": "is_physical",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMovable",
            "baseName": "is_movable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "annualDepreciation",
            "baseName": "annual_depreciation",
            "type": "number",
            "format": ""
        },
        {
            "name": "isDepreciable",
            "baseName": "is_depreciable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AssetStatusEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "AssetConditionEnum",
            "format": ""
        },
        {
            "name": "frequencyOfMaintenance",
            "baseName": "frequency_of_maintenance",
            "type": "AssetFrequencyOfMaintenanceEnum",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "number",
            "format": ""
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Set<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Asset.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AssetStatusEnum = "in_procurement" | "in_repair" | "in_disposal" | "in_use" | "in_storage" | "in_lost" | "in_stolen" | "in_leasing" | "in_rent" | "in_borrow" | "in_donation" | "others" ;
export type AssetConditionEnum = "good" | "bad" | "maintenance" ;
export type AssetFrequencyOfMaintenanceEnum = "daily" | "weekly" | "monthly" | "quarterly" | "bi_annually" | "yearly" ;

