/**
 * NGDL API
 *  This is the API document for the NGDL project. It is a work in progress and is subject to change. This documentation is provided for the purpose of testing and auditing the integrity of the platform. It is not intended for production use.<br/><br/> The API is currently in version <b>1.0.0</b>.<br/> Developed by: <b>The Boolean Technology Ltd.</b><br/> Developed for: <b>Nehemiah Grace Developer Limited</b><br/> 
 *
 * OpenAPI spec version: v1
 * Contact: tobisholanke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Transaction {
    'id'?: number;
    'logs'?: string;
    'description'?: string;
    'amount'?: number;
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'approvalStatus'?: TransactionApprovalStatusEnum;
    'approvedAt'?: Date;
    'status'?: TransactionStatusEnum;
    'paidAt'?: Date;
    'type'?: TransactionTypeEnum;
    'priority'?: TransactionPriorityEnum;
    'metaData'?: any;
    'category'?: number;
    'createdBy'?: number;
    'approvedBy'?: number;
    'statusBy'?: number;
    'folder'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "approvalStatus",
            "baseName": "approval_status",
            "type": "TransactionApprovalStatusEnum",
            "format": ""
        },
        {
            "name": "approvedAt",
            "baseName": "approved_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TransactionStatusEnum",
            "format": ""
        },
        {
            "name": "paidAt",
            "baseName": "paid_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TransactionTypeEnum",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "TransactionPriorityEnum",
            "format": ""
        },
        {
            "name": "metaData",
            "baseName": "meta_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "number",
            "format": ""
        },
        {
            "name": "approvedBy",
            "baseName": "approved_by",
            "type": "number",
            "format": ""
        },
        {
            "name": "statusBy",
            "baseName": "status_by",
            "type": "number",
            "format": ""
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TransactionApprovalStatusEnum = "pending" | "approved" | "declined" ;
export type TransactionStatusEnum = "pending" | "paid" | "unpaid" ;
export type TransactionTypeEnum = "debit" | "credit" ;
export type TransactionPriorityEnum = "urgent" | "normal" | "high" | "low" ;

